### ISSUE TITLE
What is the F1 type in the paper?

### ISSUE THREAD

**Issue by fake-warrior8** [W-lw/PCLC#1]
Hi, your code will have two results with binary slot F1 and final slot F1, which one is the F1 type in your paper?

**Comment by W-lw** [comment]
The final slot f1 indicates the standard F1 of the slot filling task which is reported in our paper. The binary slot F1  indicates the BIO F1 in the first stage, which only represents the F1 score for entity boundary recognition, regardless of the entity type. We observe the binary slot F1 to judge the relative accuracy of the classification of entity types, which is not mentioned in the paper.

**Comment by fake-warrior8** [comment]
> The final slot f1 indicates the standard F1 of the slot filling task which is reported in our paper. The binary slot F1 indicates the BIO F1 in the first stage, which only represents the F1 score for entity boundary recognition, regardless of the entity type. We observe the binary slot F1 to judge the relative accuracy of the classification of entity types, which is not mentioned in the pa

> The final slot f1 indicates the standard F1 of the slot filling task which is reported in our paper. The binary slot F1 indicates the BIO F1 in the first stage, which only represents the F1 score for entity boundary recognition, regardless of the entity type. We observe the binary slot F1 to judge the relative accuracy of the classification of entity types, which is not mentioned in the paper.

Are the results reported in your paper the best results or the average results of multiple runs? I ran  the zero-shot scenario for target domain PlayMusic one time and the final result was 24.94, which is much lower than the reported result 34.95.

**Comment by fake-warrior8** [comment]
> > The final slot f1 indicates the standard F1 of the slot filling task which is reported in our paper. The binary slot F1 indicates the BIO F1 in the first stage, which only represents the F1 score for entity boundary recognition, regardless of the entity type. We observe the binary slot F1 to judge the relative accuracy of the classification of entity types, which is not mentioned in the pa
> 
> > The final slot f1 indicates the standard F1 of the slot filling task which is reported in our paper. The binary slot F1 indicates the BIO F1 in the first stage, which only represents the F1 score for entity boundary recognition, regardless of the entity type. We observe the binary slot F1 to judge the relative accuracy of the classification of entity types, which is not mentioned in the paper.
> 
> Are the results reported in your paper the best results or the average results of multiple runs?

**Comment by W-lw** [comment]
The model you are running may not be convergent, and you can modify the config to run it more times. All reported results are the best results and the corresponding model parameters can be obtained [here](https://drive.google.com/drive/folders/1LgchJphV5gjRJULZZVvTgCMt_E2Oo7OZ?usp=sharing).

**Comment by fake-warrior8** [comment]
I found that in the log file you gave, the final F1 results for AddToPlaylist and BookRestaurant are 48.0195 and 36.7821, which is also inconsistent with the results of 59.24 and 41.36 for the zero-shot scenario in the paper.

**Comment by W-lw** [comment]
Thank you for your reminder. In this version of the code in this repository, we have simplified some of the hyperparameters to uniform hyperparameters, so the results for some domains may differ. We'll recalibrate the code later.
